linters:
  disable:
    - errcheck
  enable:
    - misspell
    - bodyclose

issues:
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA1029:"
    - linters:
        - staticcheck
      text: "SA1015:"
