project_name: weaviate
builds:
  - binary: weaviate
    goos:
      - android
      - dragonfly
      - openbsd
      - plan9
      - solaris
      - windows
      - darwin
      - linux
      - netbsd
    goarch:
      - amd64
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - arm
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  name_template: SNAPSHOT-{{.Commit}}