project_name: weaviate
builds:
  - binary: weaviate
    main: ./cmd/weaviate-server/main.go
    goos:
      - linux
    goarch:
      - amd64
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
