sudo: required
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install jq
  - curl -sL http://git.io/goreleaser | bash
before_script:
  - curl https://raw.githubusercontent.com/weaviate/weaviate/develop/docker/run-services.sh -sSf | bash
script:
  # RUN THE TEST
  # - go test -v ./test -args -api-key=$WEAVIATEKEY --server-port=8070 --server-host=localhost
  # Update nightly builds
  - goreleaser --rm-dist --snapshot --skip-validate
  # Commit back to Github
  # COMMIT