before_script: ~
branches: 
  only: 
    - master
    - develop
deploy: 
  access_key_id: GOOG4QOEU2HGYSA6CRE6
  acl: public-read
  bucket: weaviate-dist
  detect_encoding: true
  provider: gcs
  secret_access_key: 
    secure: EhYZQtPi22lksyksxWBRJxtqDcnld+CryI9L577cc+VoC8G57P9hWqrPByh22J/3X5iLf1ryNQww68RU2RJTTagPEM11O1eDwvWiso4LF2X+od6cZpwy4+FmQ0XUY7OD/65Ej0E/Hek4v0WL4B9OouWM/x5awO4iHm6ef9EniGw5wlPuqEM9cwiQWVxki8YUyKuJbWkI658eAGYl5xxj1LGQTJuCf/IiWfcQ/R9IV+PruXJ9Alh8DK4RMGDmaqbftTo5aKeidGgX+jef58yY3cgIWyDr5HAr5IFQ1hMpjHWbsl4Hhy1jc3HSS5x9BLbdD76JKHyUpTLk7t+DoM/Jks1bT2bjDBfBAtNK83JorjO95VGOZZs08FOuUylvcp+5dB49OqmAuyYiIAEe6rRK1lyQcaktIXYx30UIklTJnCVdIRu+HNbkzOadz1RlOpN3M7W2Nb5vDYzxLnfUMKJw4G1GCgUyBByNzAUUpTp2jjxR4tnVpHtbXVcWU+wVTCANV7SY41hqIFDTe5mnf8bxL9d2f1xjBsANXl1wONnVbgPZN2XaxNmHR/GvGx0h0dFO/BtYfzMu8LwrUbNKWzuxAa7VuyVfjg6wkJh1bmzP2jsZZiOWFVAlT0++1cWkq9c+oPh6tXYuvnHvvXPRigrf7AEiQss+NnGJJvitXDmo+5w=
  skip_cleanup: true
  true: 
    branch: 
      - master
      - develop
go: 
  # Always ONLY use latest Go version
  - "1.10"
language: go
install:
  - go get -t ./...
before_script:
  - sudo apt-get -qq -y update
  - sudo apt-get -qq -y install jq
script: 
  # Running Cassandra deamon
  - docker run -it --name weaviate_db_1_travis -e CASSANDRA_BROADCAST_ADDRESS=127.0.0.1 -p 7000:7000 -p 9042:9042 -v ~/cassandra:/var/lib/cassandra -d cassandra:3
  - sleep 26
  # Running Weaviate as deamon
  - nohup go run ./cmd/weaviate-server/main.go --scheme=http --port=80 --host=localhost --config="cassandra" --config-file="./weaviate.conf.json"
  # Sleep to make sure all is up and running
  - sleep 26
  # Find the correct ip, key and token
  - WEAVAITEIP=$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' weaviate_db_1_travis)
  - ROOTTOKEN=$(cat nohup.out | grep -s ROOTTOKEN|sed 's/.*ROOTTOKEN=//')
  - ROOTKEY=$(cat nohup.out | grep -s ROOTKEY|sed 's/.*ROOTKEY=//')
  # Run the tests
  - |
      # On error, quit
      set -e
      # Test!
      go test -v ./test -args -api-key=${ROOTKEY} -api-token=${ROOTTOKEN} -server-host=${WEAVAITEIP} -server-port=80 -server-scheme=http
  # Install goreleaser and create build dirs
  - |
      if [ $TRAVIS_PULL_REQUEST = "false" ]; then
          # Get latest goreleaser
          curl -s -L -o "goreleaser.tar.gz" "https://github.com/goreleaser/goreleaser/releases/download/v0.58.0/goreleaser_$(uname -s)_$(uname -m).tar.gz"
          tar -xzf goreleaser.tar.gz
          ./goreleaser --rm-dist --snapshot
          rm goreleaser goreleaser.tar.gz
          # if master, upload version nr otherwise nightly
          if [ $TRAVIS_BRANCH = "master" ]; then
              # If the folder exsists, it will fail
              if [ -e $(cat swagger/weaviate-swagger.json | jq '.info.version') ]
              then
                  # fail the script, can't overwrite an old version
                  echo "Fail, can't overwrite an old version."
                  exit 1
              fi
              mv dist $(cat swagger/weaviate-swagger.json | jq '.info.version')
              rm -r !($(cat swagger/weaviate-swagger.json | jq '.info.version'))
          else
              # if master, upload version nr
              mv dist nightly
              rm -r !(nightly)
          fi
      fi
services: 
  - docker
sudo: required
