language: go
go:
  - 1.8
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get ./...
script:
  - curl https://get.dgraph.io -sSf | bash
  - sleep 60
  - dgraph --memory_mb 2048
  - go run ./cmd/weaviate-server/main.go --scheme=http --port=8070 --host=localhost --config=graph --config-file=weaviate.conf.json
  - sleep 40
  # - export WEAVIATEKEY=$(grep "ROOTKEY=" nohup.out | cut -d "=" -f 2)
  - go test -v ./test -args -api-key=$WEAVIATEKEY --server-port=8070 --server-host=localhost