addons:
  hosts:
    - db
after_success:
  # Login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    # Build & Push docker images on dev and master
    if [ $TRAVIS_PULL_REQUEST = "false" ]; then
      if [ $TRAVIS_BRANCH = "master" ]; then
        # collect the latest version
        LATESTVERSION=$(git show --oneline HEAD:$WEAVIATESCHEMAFILE | jq -r ".info.version")
        # Build master
        DOCKERTARGET=weaviate_base     
      elif [ $TRAVIS_BRANCH = "develop" ]; then
        # collect the latest version
        LATESTVERSION=unstable
        # Build master
        DOCKERTARGET=development
      fi
      # Build & Push
      docker build -t creativesoftwarefdn/weaviate:$LATESTVERSION --target $DOCKERTARGET .
      docker push creativesoftwarefdn/weaviate:unstable
    fi
before_script: ~
branches: 
  only: 
    - master
    - develop
dist: xenial
go: 
  - "1.11"
env:
  matrix:
  # Disable GraphQL tests and force using modules.
  - GO111MODULE=on GRAPHQL_TESTS=skip
  global:
  # location of the open-api specs
  - WEAVIATESCHEMAFILE=openapi-specs/schema.json
  # how to autobump semver style
  - SEMVERBUMPTYPE=patch
  # secure values
  - secure: QH/qM6TuOZtNnNY8aKZPYB8uya3IYNVchvfyX28Tq5Kwwfj9CZX/m9Hac7lP1xOZyKdKMT4PAwVxUEhtQENJfymckQCFHVtoAU4vbVrUe8riAEBaWKNGM1rmPpU6gpdQ3oKDfBgSp5Sb4V+WhgCcN5u9xKC0ybURBVWUNhRyib8qEEe0w+CpJGaVdvtVFxDh2DuvJqZq+k416YIGY+83KhldQ/FKG0wRu9lGooOtcCIcSdJl+V8AaRByxsLa9JsSLoXsTHULdJfnP3g/tf4o36fA/4zbK+e8MLMGhfVmRQd5ow06E//H8Zct2OazTO8R+7f+01X5OcQAviXkyVTLcZ/xekoM/g+h9JWzF63uqAE1fq00hEs2tV4iT82xpyhevUTXGzs1460u+ESbHQJK0SjbpAQTRllKDrACgYQDKjE32EhT2TkEE5u+DZ/u19FHPsA6txjqFh0SXHKtpSk2hVdnpg7AawSY/QUc+sGp3enc6HAT/87cKaH9gSCxgI/KzUaXfEEfLp9hScckNpy9roaSvLmotGLxdpBnFpdmWaG56M/ohxTPhu5/FjIygIu+q2rDl2DwkPzeyFbsMjTAX++zBmpxW/D1GqVr+z5BxoTBJaJKO1K4vSay2q8GFdQeJXv3hIGFjt6qRhMWY83N9DZy4dOGTdE12nrQYA6oHqM=
  - secure: BOTUCkJrvKXMnCAfZN6x+gKgCI+TGnUEy5H0DxJ+NrxWsFwFXUiPAGR5kRMnRnh1uQ72xURwid/3lMd0ARaX7ZiG2ThoaEceHF0BVDRcD5sXBYtFOJP7OTHkbklxy/RyUny/GTmgfZDF4bKJGSDrUNbXlE8yeDF4kDWlThDuEaAYAefTmnFTaSJNYqyDyJaWfD04dgZ/6tNINHvTZjGBtIt0WnBp+LC9D0YGNuqSfHhkxmsVcPI+6lWynnWG2yU0L1Euw+OgqFV6qv8K3UHftnEoClVRmcKUry+FR0wW6Ah7WLxnH3Bkqwg4kqbxi8NdGdxM2TtRwkEn4vt1sxH02uaLZasdbRsRIcuOJ9Zq42c61GB9o3riNp7gTtA7nqjqHGDJVyYkDaNMKK+91FHefagtgdU/htrLPX5CemPH21AmIU51OfVTd2mAEan343a62gk3zVOKv6gHgfqtoxMWWquQUqXHyMdyPQ5EJFLsnTSpdSV0SkSZO9Um+sQ+BRC3t7D5QaP3NLN2X4nEOqAOdfI4JzwZX7sREUugI87zbrRAAXi+KoO+mfmcywL7hegKquctxv2TBt3U+pmT1ieZacArjnK4iTKK7NXPIUXXu9Fy3pnO3DSwtWu/RhA96UmuJZyca1eI1bo0zwPGt4bfLJGFd25/O1ttM54Z7MvBvG8=
  - secure: n4CXkJJlfkzXxBUW8lPd6nCxkRwt4+Z9q9c094OX6oJDnhBdItXqxTizFE1ClH+nG7v/KunBVK0DVbPuH19JQJ/OrcsNGJ2NBFHCW5gmAwexD7D1Zn9JFQolD711l7YufqPeC9275X8UMK/sbZK6KN8bmrAi8iBhE9U8vi9scsHZLUfe1G0YxUgjcPX8fgM8YMyJf6Y0wef0j7GyU2CK6qNtJ5QdNn7z3YzWTsQPGsy4CNCitATT69XqQhGM5rwsx08cTAxmRqHqo/j2bC4Ksy/bK+phLYqtuAT+rch1zNrEM2tAxLj/hFLQTb7Dzg1xEThhwkVmGpLQOG50HBMDW39jgirJlAfRK0LmHcu3VD/esPL6neyBUfNv/DxLNLP7K1dNGoe7wHG9hjSzzm3YmIb31J/v79hxoPGLYlLYtiF4oZOatWs2V9HD/WY2zus5y8wYMijSn7DCuUUM29pL/4nhhJipHIqD51VnzTkyVQeBCdAogskjKV6h06/SSxXJIydNeKJ/D+FUa2u8QvNRaNLqoi9f0LttqUXg5CVXB4yWQ/VLvf4Wqa2xbTXDiobv4RQ93urUMIKETvCADpqW3lSBPusOqYbp1oFal5zS6LYa6mWfHPQd4LIsvXi2+RqUa8D2EFb/jOh6ZsYwktt8fASjfKKrLnoJ309LRZwrrMU=
  - secure: YkdZm+69xAflwRS6jj1F7EBpxPsqBOupEIAf3NMfnIsRoBE3FDxcvoIHV+MO9It8rZ0cv4rz44I+g1+7kk7i8OFSLYccWnhvGDoLLHCRv9UsehiyPA/ESitsrBKyNVIYoMM+6jII4lNXS/IdwNiGp3ATzUJZP+xAjTMXtByDZWNtRZehTpM+dRK6PKvSS917YT+aW4CoHKRbgEJjimIt3tL/PIc8b9+qtJ80gdgUaFOWnKEiDxQNbe/K7tp+l8Irx/duw1sPZR6MZvhzF2rrVSUOj4SS2XSJZefRzKQOtLTGapkt4VtgcOy4IT6cVHmVgeAlG6rhyHKu9ohgMc8lTnCoxdh4ZvGLBPw7XtbwrlyxqgrchwFH4TS++YnKPR/7SfEKF3MFiXLQQacX1vTdKGzq6ZbsQbKmWtPCbaR3ziWG80H4CrXw5m2lYyfgZoZ1O6AQ+QhWskljwy6q0Ncu9qRjr7mnIsZeIf0sh3CWLJVyHPGzgXn2mzW7YDxqcYqhaSvFuROIPxhZIyemmQjLLn/GkdjQug3CXWuhSqJOpNd9bRdRgjmH1qNxcY5wotB2hvbu9NTXErxCem9Zl12mMyNzyGSevD8auMC4Y9f/Kqxg+fRN9P0djJSeguAxJpa0eDbhuKp0lrVWIjdmUynVdSV/VEaNoN9PQLUt8/H2wmI=
  - secure: BdKvquvgHePJVWyIH15D5Ttarqyf0gYDksj3A0CjOJugt9/XqYb3vhjYBCrwI+Y3MIv0MXKzC6WNV6/HJksWYXN1vLvTmdCzd0AYnOol4Ruf4fAMPYTjwMHN6M0/DbOfZTvvlW2ztSr+9rzbMMcN/wZW2N/AG1sfV5EbOEQx81Kh9l0IPrWXgvSZf8k/7HvkPMnRdjTRIzhNojyJInwBii3GUedBcj/eCQY/9Qxaz+bD0XqLDfvscL6gJtSxxl/4dBV6n/NXGUzLrVFOo6poz2XQR9oIFrp0Fd3bPuISfpaQQJQ5o7XjtNcGXowZrtZr7jE6+MfIN8pZAMuFWHL72sqI8gccDGru22k9tKKt/iKl0aiRWdi3iZ2MM5c8da0x3ZwfpFZLodMohsa9o68wzKgLDwbR/8JVYl7mswkpKfhz52xJNBTQmE8TirfnaLpzMP8BUTURMzF9UTZGdUwO5oKtM/SV6RXcBvpe0iuHMFBv0iR1fAze/vIA9YraaCBPmWcko9qCTEKrb9dTdmeFaYposNR9W40pApEGiThxRX9LBB9vX7Ow5foqzTC9usXq58puTKggTERs/Mqnt8F14UhwJasQTYNTuFI4mo3M7lK/3zwPuDFfD2vuzPaLCYf3tt19g93j3Yxgp/SFYjqDIBjR1xMbFIFhoZpkdHeCF8g=
language: go
install:  
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - wget https://raw.githubusercontent.com/creativesoftwarefdn/semver-tool/master/src/semver
  - chmod +x semver
before_script:
  - sudo apt-get -qq -y update
  - sudo apt-get -qq -y install jq coreutils python3
  - |
    # Validate if the open-api schema needs to be bumped
    if [ $TRAVIS_PULL_REQUEST = "false" ]; then
      # PREVIOUSSEMVER = comparison of the current HEAD of WEAVIATESCHEMAFILE with the previous commit. More info: https://github.com/fsaintjacques/semver-tool/blob/master/README.md
      PREVIOUSSEMVER=$(./semver compare $(git show --oneline HEAD:$WEAVIATESCHEMAFILE | jq -r ".info.version") $(git show --oneline HEAD~1:$WEAVIATESCHEMAFILE | jq -r ".info.version"))
      # Determine if the version should be bumped
      if [ "$PREVIOUSSEMVER" -eq 0 ]; then
        # Bump the version + pipe to WEAVIATESCHEMAFILE.tmp + rm and mv WEAVIATESCHEMAFILE.
        echo $(jq -r '.info.version = $NEWVERSION' --arg NEWVERSION "$(./semver bump $SEMVERBUMPTYPE $(git show --oneline HEAD:$WEAVIATESCHEMAFILE | jq -r ".info.version"))" $WEAVIATESCHEMAFILE) | jq . > $WEAVIATESCHEMAFILE.tmp && rm $WEAVIATESCHEMAFILE && mv $WEAVIATESCHEMAFILE.tmp $WEAVIATESCHEMAFILE
        # build with new version
        ./tools/gen-code-from-swagger.sh
        # push back to Git
        git config credential.helper "store --file=.git/credentials"
        echo "https://${GH_TOKEN}:@github.com" > .git/credentials
        git add -A
        git commit -m "🤖 semver bump"
        git push origin HEAD:${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
        # exit 0 will trigger a new build
        travis_terminate 0
      elif [ "$PREVIOUSSEMVER" -eq -1 ]; then
        echo "Semver is behind the latest commit. This issue should be resolved and the version should be set to at least $(./semver bump patch $(git show --oneline HEAD~1:$SCHEMAFILE | jq -r ".info.version"))"
        travis_terminate 1
      fi
    fi
  # Verify that the code is properly formatted.
  - if [[ -n "$(gofmt -l .)" ]]; then echo "The following files were not formatted properly!"; gofmt -l .; exit 1; fi
  # Run Weaviate backed by JanusGraph
  - tools/test/run_ci_server.sh || travis_terminate 1
script: 
  # Verify dev setup is not broken
  #- ./tools/test/import_journey.sh || travis_terminate 1
  # Run all tests
  - |
    # Load the test schema in weaviate.
    go run ./tools/schema_loader -action-schema test/schema/test-action-schema.json -thing-schema test/schema/test-thing-schema.json
    # Load the fixtures for the GraphQL acceptance tests
    go run ./tools/schema_loader -action-schema test/acceptance/graphql_resolvers_local/fixtures/actions_schema.json -thing-schema test/acceptance/graphql_resolvers_local/fixtures/things_schema.json
    go run ./tools/fixture_importer/ -fixture-file test/acceptance/graphql_resolvers_local/fixtures/data.json
    # Prepare test reporter
    ./cc-test-reporter before-build
    # Run all tests
    for pkg in $(go list ./... | grep -v main); do
        if ! go test -race -v -coverprofile=$(echo $pkg | tr / -).cover $pkg; then
          echo "Test for $pkg failed" >&2
          travis_terminate 1
        fi
    done
    echo "mode: set" > c.out
    grep -h -v "^mode:" ./*.cover >> c.out
    rm -f *.cover
    ./cc-test-reporter after-build
services: 
  - docker
sudo: required
