sudo: required
language: go
branches:
  except:
  - master
go:
- 1.8.3
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get install jq
- go get github.com/goreleaser/goreleaser
before_script:
- curl https://git.io/vdwgr -sL | bash
script:
- goreleaser --rm-dist --snapshot --skip-validate
- mkdir -p nightly
- mv dist/*.zip nightly
- mv dist/*.txt nightly
- rm -rf dist
- mv nightly dist
deploy:
  provider: gcs
  access_key_id: GOOG53DEMILDMQ2IJSEX
  secret_access_key:
    secure: E6dB/4F5jxfbmc4jqgDG1gQFaz3P3wn1zCGtsb5FS5Gmn2F6+9ki0uNpOz1qiPpSOjwZjeOSGeBAsoEbOgoou1BpJ4J17Rr7L9/S2TXbRyp6AiCa5QpjUMHUZfF4DdDg7hgxsuTAqvcPT0u7wc8lY1WXL7IzAdfIDGLibNzDdjUWNUd9zL5BSVZ3YJoK4zyERoGPNWyWIE4nuBHP3BUcsCjg6ax34onmWs8TfTpK//VJi8fybeQizMbkPP6iWLF+NCvtw1EaTeh7vbuuLY3VxFQM0cJk0SuJLhrqczHHtQnYZI4X7QlsnP0+xfy6PmAOcshstHRIePiTM2e6XsIbC3eqEzN8LHb4tAfpjCWgyEYWMZ+dMXeAE4WERk1Wal1ENYQgS1+4f0Hib6DNu9CDjRS5DNbbyHSC3HdQWJJ00hfHPKmJzrMNgbhFjHl1yTIY6Y5cLv5uaXGZXV/sCTwSBsqHMEem0ci9UsB7O+segSy97JsEqbixv6jBzh8AXQ6WoB3HoNnJVdlZvvBHTWvx0fD94l9WJeRC2w+FLHSqnouBQcy+xGEVYP5HiZQNejaJEkZ4tXD7BPZqSYv1VqgcW3mHKykuboeTw9qrjDPPWLziK2ZQVUJnImDajgxnq01ybOGQHcbO4fZepscVpouDdwjfTm1Ka1yIBMz/JBItal8=
  bucket: weaviate-dist
  # skip_cleanup: true
  acl: public-read
  local-dir: nightly
  detect_encoding: true
  on:
    branch: develop