##
# This docker-compose is used in development of Weaviate. To run a stable
# version see the docker-compose files in ./docker-compose/runtime/{language}
##
version: '3.4'
services:
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.0.2
    ports:
      - "9999:9999"
    environment:
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://host.docker.internal:8080
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      LOG_LEVEL: debug
  keycloak:
    image: jboss/keycloak:5.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/weaviate-realm.json
    volumes:
      - ./tools/dev/keycloak/weaviate-realm.json:/tmp/weaviate-realm.json
    ports:
      - "9090:8080"
  t2v-transformers:
    image: semitechnologies/transformers-inference:distilbert-base-uncased
    ports: 
      - "8000:8080"
