###                        _       _
#__      _____  __ ___   ___  __ _| |_ ___
#\ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
# \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
#  \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
#
# Copyright © 2016 - 2018 Weaviate. All rights reserved.
# LICENSE: https://github.com/creativesoftwarefdn/weaviate/blob/develop/LICENSE.md
# AUTHOR: Bob van Luijt (bob@kub.design)
# See www.creativesoftwarefdn.org for details
# Contact: @CreativeSofwFdn / bob@kub.design
###
version: '3.2'
services:
  db:
    image: cassandra:3
    volumes: 
      - ~/cassandra:/var/lib/cassandra
    ports: 
      - 7000:7000
      - 9042:9042
    environment: 
      CASSANDRA_START_RPC: "true"
  weaviate-broker:
    image: creativesoftwarefdn/weaviate-broker:latest
    ports:
      - 1883:1883
      - 8888:8888
  weaviate:
    build:
      context: .
      args:
        config_file: ./weaviate.conf.json
        action_schema: ./test/schema/test-action-schema.json
        thing_schema: ./test/schema/test-thing-schema.json
        release: nightly
        platform: linux
        architecture: amd64
    depends_on:
      - "db"
      - "weaviate-broker"
    ports: 
      - 80:80
      - 443:443
    environment:
      - WEAVIATE_CASSANDRA_DB_HOST=db
