version: '3.4'
services:
  weaviate:
    image: weaviate/test-server
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    depends_on:
      - janus
      - genesis_fake
    restart: on-failure:0
    ports:
     - "8080:8080"
    environment:
      DEBUG: 1
  genesis_fake:
    build:
      context: .
      dockerfile: Dockerfile
      target: genesis_fake
    restart: on-failure:0
    ports:
      - "8090:8090"
    environment:
      REMOTE_PEER_NAME: RemoteWeaviateForAcceptanceTest
      REMOTE_PEER_URI: http://remote_weaviate_fake:8081
      LOCAL_PEER_URI: http://weaviate:8080
      ACCEPTANCE_TEST: "on"
  remote_weaviate_fake:
    build:
      context: .
      dockerfile: Dockerfile
      target: remote_weaviate_fake
    restart: on-failure:0
    ports:
      - "8081:8081"
  janus:
    image: creativesoftwarefdn/janusgraph-docker:0.2.0
    depends_on:
      - db
      - index
    ports:
     - "8182:8182"
     - "8184:8184"
    environment:
     - DEV_MODE=true
  db:
    image: scylladb/scylla:2.0.1
    ports:
     # http://docs.scylladb.com/kb/posix/
     # REST API
     - "10000:10000"
     # CQL ports (native_transport_port)
     - "9042:9042"
     # Thrift (rpc_port)
     - "9160:9160"
     # Internode
     - "7000:7000"
     - "7001:7001"
     # JMX
     - "7199:7199"
     # Prometheus monitoring
     - "9180:9180"
     - "9100:9100"
    volumes:
     - ./data/scylla/data:/var/lib/scylla
  index:
    image: elasticsearch:5
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - ./data/elasticsearch/data:/usr/share/elasticsearch/data
