version: '3.4'
services:
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v0.4.20
    ports:
      - "9999:9999"
    environment:
      LOG_LEVEL: debug
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.95
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://docker.for.mac.localhost:8080
