# With this compose file you'll be able to start a development version of Weaviate,
# including it's backing database, contextionary, and demo data set.
#
# Usage:
#   $ docker-compose -f docker-compose.yml up
#
# It will be finished when the output of
#   $ docker-compose -f docker-compose.yml ps
#
#   mentions that the importer has existed with status 0,
#   as is shown in the example output below
#
#                  Name                             Command               State                                   Ports
#    --------------------------------------------------------------------------------------------------------------------------------------------------
#    weaviate_db_1                       /docker-entrypoint.py            Up       0.0.0.0:10000->10000/tcp, 0.0.0.0:7000->7000/tcp,
#                                                                                  0.0.0.0:7001->7001/tcp, 0.0.0.0:7199->7199/tcp,
#                                                                                  0.0.0.0:9042->9042/tcp, 0.0.0.0:9100->9100/tcp,
#                                                                                  0.0.0.0:9160->9160/tcp, 0.0.0.0:9180->9180/tcp
#    weaviate_index_1                    /docker-entrypoint.sh elas ...   Up       0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp
#    weaviate_janus_1                    /bin/bash -e /workspace/ja ...   Up       0.0.0.0:8182->8182/tcp, 0.0.0.0:8184->8184/tcp
#    weaviate_weaviate_1                 /bin/weaviate --host 0.0.0 ...   Up
#    weaviate_weaviate_demo_importer_1   ./tools/dev/import_demo_da ...   Exit 0
#
# You'll be able connect to Weaviate with the following key/token pair:
# 
#  Key:   657a48b9-e000-4d9a-b51d-69a0b621c1b9
#  Token: 57ac8392-1ecc-4e17-9350-c9c866ac832b
#
# NOTE:
#   If you abort the janusstack hard (not a clean shutdown), it won't come up again;
#   destroy the containers and retry.
version: '3.4'
services:
  weaviate:
    image: weaviate/dev-server
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - janus
    restart: on-failure:0
    ports:
     - "8080:8080"
  weaviate_demo_importer:
    image: weaviate/demo_importer
    command: ["-weaviate-url", "http://weaviate:8080/weaviate/v1/"]
    build:
      context: .
      dockerfile: Dockerfile
      target: data_importer
    depends_on:
      - weaviate
    restart: on-failure:0
  janus:
    image: creativesoftwarefdn/janusgraph-docker
    depends_on:
      - db
      - index
    ports:
     - "8182:8182"
     - "8184:8184"
  db:
    image: scylladb/scylla:2.0.1
    ports:
     # http://docs.scylladb.com/kb/posix/
     # REST API
     - "10000:10000"
     # CQL ports (native_transport_port)
     - "9042:9042"
     # Thrift (rpc_port)
     - "9160:9160"
     # Internode
     - "7000:7000"
     - "7001:7001"
     # JMX
     - "7199:7199"
     # Prometheus monitoring
     - "9180:9180"
     - "9100:9100"
    volumes:
     - ./data/scylla/data:/var/lib/scylla
  index:
    image: elasticsearch:5
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - ./data/elasticsearch/data:/usr/share/elasticsearch/data
