version: '3.4'
services:
  weaviate-playground:
    image: creativesoftwarefdn/weaviate-playground:unstable
    ports:
     - "80:80"
  janus:
    image: creativesoftwarefdn/janusgraph-docker:0.2.0
    depends_on:
      - db
      - index
    ports:
     - "8182:8182"
     - "8184:8184"
    environment:
     - DEV_MODE=true
    volumes:
      - ./janusgraph.properties:/janusgraph-config/janusgraph.properties
  db:
    image: scylladb/scylla:2.0.1
    ports:
     # http://docs.scylladb.com/kb/posix/
     # REST API
     - "10000:10000"
     # CQL ports (native_transport_port)
     - "9042:9042"
     # Thrift (rpc_port)
     - "9160:9160"
     # Internode
     - "7000:7000"
     - "7001:7001"
     # JMX
     - "7199:7199"
     # Prometheus monitoring
     - "9180:9180"
     - "9100:9100"
  index:
    image: elasticsearch:5
    ports:
     - "9200:9200"
     - "9300:9300"
  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.8
    ports:
      - "2379:2379"
    entrypoint: /usr/local/bin/etcd
    command: 
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--listen-client-urls"
      - "http://0.0.0.0:2379"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster-state"
      - "new"
