name: Feature request
description: Suggest an idea for this project.
title: "Feature: "
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |

        * Thanks for taking the time to fill out our feature request form :)
        * For questions, ask in [Slack](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw).
        * Before raising a feature request issue, please search for [existing feature request issues](https://github.com/semi-technologies/weaviate/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) to avoid creating duplicates.

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the Weaviate's [Code of Conduct](https://github.com/semi-technologies/weaviate/blob/master/CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    attributes:
      label: Feature description
      description: |
        - A clear and concise description of what the feature is. 
        - Please explain why and how this feature should be implemented. If applicable, provide examples.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? 
      description: A clear and concise description of what the problem is.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context 
      description: Add any other context like alternative solutions or screenshots.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Have you checked to see if this issue has been raised before?
      description: Have you looked for a similar bug on Google or in our older issues?
      options:
        - label: I checked and didn't find similar issue
          required: true
      