database:
  name: janusgraph
  database_config:
    url: http://localhost:8182
    analytics_engine:
      enabled: true
      type: spark-analytics-api
      url: http://localhost:8100
authentication:
  anonymous_access:
    enabled: false
  oidc:
    enabled: true
    issuer: http://localhost:9090/auth/realms/weaviate
    username_claim: email
    groups_claim: groups
    client_id: demo
    skip_client_id_check: false
authorization:
  admin_list:
    enabled: true
    users:
    read_only_users:
      - john@doe.com
analytics_engine:
  enabled: true
  defaultUseAnalyticsEngine: false
configuration_storage:
  type: etcd
  url: http://localhost:2379
contextionary:
  url: localhost:9999
query_defaults:
  limit: 20
debug: true
logging:
  interval: 1
  enabled: false
  url: http://telemetry_mock_api:8087/mock/new
network:
  genesis_url: http://localhost:8090
  public_url: http://localhost:8080
  peer_name: bestWeaviate
telemetry:
  disabled: true
