authentication:
  anonymous_access:
    enabled: true
database:
  name: janusgraph
  database_config:
    url: http://localhost:8182
configuration_storage:
  type: etcd
  url: http://localhost:2379
contextionary:
  url: localhost:9999
schemas:
  Thing: test/schema/test-thing-schema.json
  Action: test/schema/test-action-schema.json
query_defaults:
  limit: 100
debug: true
logging:
  interval: 1
  enabled: true
  url: http://mock_api:8087/mock/new
telemetry:
  disabled: true
