database:
  name: janusgraph
  database_config:
    url: http://janus:8182
configuration_storage:
  type: etcd
  url: http://etcd:2379
contextionary:
  knn_file: contextionary/contextionary.knn
  idx_file: contextionary/contextionary.idx
network:
  genesis_url: http://genesis_fake:8090
  public_url: http://localhost:8080
  peer_name: bestWeaviate
limit: 100
debug: true
logging:
  interval: 1
  enabled: true
  url: http://telemetry_mock_api:8087/mock/new
development:
  external_instances:
    - url: http://localhost:8080
    - url: http://127.0.0.1:8080
