authentication:
  anonymous_access:
    enabled: true
vector_index:
  enabled: true
  url: http://localhost:9201
  denormalizationDepth: 2
configuration_storage:
  type: etcd
  url: http://localhost:2379
contextionary:
  url: localhost:9999
query_defaults:
  limit: 100
debug: true
logging:
  interval: 1
  enabled: false
  url: http://telemetry_mock_api:8087/mock/new
network:
  genesis_url: http://localhost:8090
  public_url: http://localhost:8080
  peer_name: bestWeaviate
telemetry:
  disabled: true

# feature toggle
esvectorOnly: true
