---
authentication:
  anonymous_access:
    enabled: true
database:
  name: janusgraph
  database_config:
    url: http://janus:8182
configuration_storage:
  type: etcd
  url: http://etcd:2379
contextionary:
  knn_file: contextionary/contextionary.knn
  idx_file: contextionary/contextionary.idx
  stopwords_file: contextionary/stopwords.json
limit: 100
debug: false
telemetry:
  disabled: true
query_defaults:
  limit: 25

