version: '3.4'
services:
  weaviate-playground:
    image: semitechnologies/weaviate-playground:latest
    depends_on:
      - weaviate
    ports:
     - "80:80"
  weaviate:
    image: semitechnologies/weaviate:0.19.4
    command: 
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--scheme"
      - "http" 
      - "--config-file"
      - "config.yaml"
    depends_on:
      - janus
    restart: on-failure:0
    ports:
     - "8080:8080"
    volumes:
     - ./config.yaml:/config.yaml
  contextionary:
    image: semitechnologies/contextionary:en0.8.0-v0.3.3
    ports:
      - "9999:9999"
    environment:
      SCHEMA_PROVIDER_URL: etcd:2379
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
  janus:
    image: semitechnologies/janusgraph-docker:0.3.1
    depends_on:
      - db
      - index
    ports:
     - "8182:8182"
     - "8184:8184"
    restart: on-failure:0
    environment:
     - DEV_MODE=true
    volumes:
      - ./janusgraph.properties:/janusgraph-config/janusgraph.properties
      - ./gremlin-server.yaml:/janusgraph-config/gremlin-server.yaml
  db:
    image: scylladb/scylla:2.0.1
    ports:
     # http://docs.scylladb.com/kb/posix/
     # REST API
     - "10000:10000"
     # CQL ports (native_transport_port)
     - "9042:9042"
     # Thrift (rpc_port)
     - "9160:9160"
     # Internode
     - "7000:7000"
     - "7001:7001"
     # JMX
     - "7199:7199"
     # Prometheus monitoring
     - "9180:9180"
     - "9100:9100"
  index:
    image: elasticsearch:5
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
     - ES_JAVA_OPTS=-Xms300m -Xmx300m
  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.8
    ports:
      - "2379:2379"
    entrypoint: /usr/local/bin/etcd
    command: 
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--listen-client-urls"
      - "http://0.0.0.0:2379"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster-state"
      - "new"
  esvector:
    image: semitechnologies/esvector:7.1.0
    environment:
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms500m -Xmx500m
      discovery.type: single-node
    ports: 
      - "9201:9200"
      - "9301:9300"
