version: '3.4'
services:
  weaviate-playground:
    image: semitechnologies/weaviate-playground:latest
    depends_on:
    - weaviate
    ports:
    - 80:80
  weaviate:
    image: semitechnologies/weaviate:0.21.3
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    - --config-file
    - config.yaml
    depends_on:
    - esvector
    restart: on-failure:0
    ports:
    - 8080:8080
    volumes:
    - ./config.yaml:/config.yaml
  contextionary:
    image: semitechnologies/contextionary:nl0.10.0-v0.4.1
    ports:
    - 9999:9999
    environment:
      SCHEMA_PROVIDER_URL: etcd:2379
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.8
    ports:
    - 2379:2379
    entrypoint: /usr/local/bin/etcd
    command:
    - --name
    - s1
    - --data-dir
    - /etcd-data
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://0.0.0.0:2379
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --initial-advertise-peer-urls
    - http://0.0.0.0:2380
    - --initial-cluster
    - s1=http://0.0.0.0:2380
    - --initial-cluster-token
    - tkn
    - --initial-cluster-state
    - new
  esvector:
    image: semitechnologies/esvector:7.1.0
    environment:
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms500m -Xmx500m
      discovery.type: single-node
    ports:
    - 9201:9200
    - 9301:9300
